baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Swarm Blog'
theme = 'swarm-blog'

contentDir   = "content"
enableInlineShortcodes = true
defaultContentLanguage = 'en'

[languages]
  [languages.en]
    title = 'Swarm News Blog'
    weight = 5
    contentDir = 'content'
  [languages.foundation]
    title = 'Swarm Foundation Blog'
    weight = 4
    contentDir = 'content/foundation'
  [languages.hive]
    title = 'Swarm Hive Blog'
    weight = 3
    contentDir = 'content/hive'
  [languages.wam]
    title = 'We Are Millions Blog'
    weight = 2
    contentDir = 'content/wam'
  [languages.fds]
    title = 'Fair Data Society Blog'
    weight = 1
    contentDir = 'content/fds'

[outputs]
  home = ["HTML","JSON"]
  section  = ["HTML"]

[permalinks]
  posts = ':year/:title/'
  categories = '/c/:title'

[taxonomies]
  category = "categories"

[related]
  includeNewer = true
  threshold = 80
  toLower = true
[[related.indices]]
  name = 'categories'
  weight = 10
[[related.indices]]
  name = 'date'
  weight = 40