---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: content/_index.md
  label: Home
- type: directory
  path: content/foundation/posts
  label: Swarm Foundation
  create: documents
  match: "*"
  templates:
  - post
- type: directory
  path: content/fds/posts
  label: FDS
  create: documents
  match: "*"
  templates:
  - post
- type: directory
  path: content/hive/posts
  label: Swarm Hive
  create: documents
  match: "*"
  templates:
  - post
- type: directory
  path: content/wam/posts
  label: WAM
  create: documents
  match: "*"
  templates:
  - post
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.104.3
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
